name: First Workflow

on:
  repository_dispatch:
    types: [your_specific_workflow_event]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: my-step
        run: echo "Hello World!"
